### ISSUE TITLE
Loading component not working inside preload

### ISSUE THREAD

**Issue by brpaz** [cerebroapp/cerebro-ui#1]
I was following the example of using the "Preload" element to wrap a promise response, but I get an error on Loading element:

`Preload.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

If I dont specify a Loader everything works fine. I also tried to create my own Loader component but I got the same problem. Not really sure whats going on.

Here is my code for reference:

```
const { Preload, Loading } = require('cerebro-ui');
const NoteContents = require('./Preview/NoteContents');

const NotePreview = (key, promise) => (
  <Preload key={key} promise={promise} loader={Loading}>
    {(promiseResult) => <NoteContents key={key} contents={promiseResult} /> }
  </Preload >
);

```

And its being called like this:

```
 getPreview: () => {
                const promise = evernoteService.getNoteContent(note.guid);
                return NotePreview(note.guid, promise);
              }
```

**Comment by KELiON** [comment]
Hey, @brpaz! It should work if you use `loader={<Loading />}`. I'd say that this API is a bit broken and would be much better to allow developers to pass any argument as a stateless component, like `loading={() => <Loading />}`. I've created #2 to fix this api

**Comment by ogustavo-pereira** [comment]
This issue is very old, I will close it because it is likely that we will migrate the react version and that will change
