### ISSUE TITLE
Preload `loader` prop should allow stateless components

### ISSUE THREAD

**Issue by KELiON** [cerebroapp/cerebro-ui#2]
Currently `loader={<Loading />}` works, but it looks a bit ugly, would be much better to allow developers to pass any component, i.e. as a functional component `loader={() => <Loading />}` (currently it fails with PropTypes check)

**Comment by ogustavo-pereira** [comment]
This issue is very old, I will close it because it is likely that we will migrate the react version and that will change

**Comment by ogustavo-pereira** [comment]
cc @KELiON
