### ISSUE TITLE
fix(MacOS): nodobjc dependency error

### ISSUE THREAD

**Issue by dubisdev** [cerebroapp/cerebro-ui#8]
I'd also like to help here. I've got the same issue as in #607, the app won't show at all. Just to see what happens, I've tried locally checking out cerebro-ui and manually removing the places where `nodobjc` is used. The app starts, though there are still plenty of errors.
If help is wanted, I'd love to contribute.

_Originally posted by @ChFlick in https://github.com/cerebroapp/cerebro/issues/602#issuecomment-1280893230_

**Comment by dubisdev** [comment]
Hi @ChFlick

As you can see we are having some issues with the `nodobjc` dep in MacOS. This dependency is used [in this file](https://github.com/cerebroapp/cerebro-ui/blob/master/src/FileIcon/getFileIcon/mac.js) to get the icon of an app/file.

I see it is really outdated (latest version was released in dec 2015) and I found a new one that could do the same: [file-icon](https://github.com/sindresorhus/file-icon)

Maybe you could migrate the funcionality to this new dependency and test if it works.

The code in the file is really outdated so feel free to update the imports and exports to ESM code. You can compile the code by using `yarn build`.

Note: I see the latest (v5) has ben migrated to ESM modules, it might fail because cerebro supports only commonjs deps so I would recommend you to use the previous v4.


Thanks for ccontributing to Cerebro 🙌

**Comment by ChFlick** [comment]
Hi, so I've looked at it a bit, and I think `file-icon` won't work, or at least needs some more work, as it requires the `fileicon` binary to be bundled with it to execute it.
Actually, the "windows version" using the electron functionality should work for mac as well, so I think the distinction isn't neccessary.

I'm having some trouble running the `cerebro-ui` + `cerebro` locally, so I couldn't test it yet. It's throwing several react errors for me, in particular that `useState` is not defined. When I add it to the dependencies it throws some errors that "hooks cannot be called outside a functional component". Both errors don't really make sense to me here - any clue?

**Comment by dubisdev** [comment]
Using `app.getFileIcon` should do the trick yes!

I'm investigating on `useState` issue.

**Comment by dubisdev** [comment]
Hi @ChFlick I think useState and useRef problems are solved now. There is a pending PR review with the fix for this (#9). If you want, you can test your implementation with the code in that PR.

Hope this helps!
